# Generated by Django 4.2.4 on 2023-08-03 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reservation_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 3, 20, 23, 41, 200740)),
        ),
    ]
